# Generated by Django 3.0.4 on 2020-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_socialmediasettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
