# Generated by Django 3.0.4 on 2020-06-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_circleimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircleImages',
        ),
    ]
