# Generated by Django 3.0.4 on 2020-06-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_roundtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoundText',
        ),
    ]
