# Generated by Django 3.0.4 on 2020-06-21 19:17

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200621_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add your text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.SimpleRichTextBlock()), ('embed_block', wagtail.embeds.blocks.EmbedBlock()), ('html_block', wagtail.core.blocks.RawHTMLBlock()), ('image_chooser_block', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
